name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: wkrpcindemo
  AZURE_GROUP_NAME: wkrpcindemo
  AZURE_LOCATION: westus

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore cinnug.csproj
      - name: Build
        run: dotnet build cinnug.csproj --configuration Release --no-restore
      - name: Publish
        run: dotnet publish cinnug.csproj --configuration Release --output ./output

      # Create/Update Azure App Service Plan and App Service
      - name: Deploy
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - run: |
          az group create -n ${{ env.AZURE_GROUP_NAME }} -l ${{ env.AZURE_LOCATION }}
          az group deployment create -n ghaction -g ${{ env.AZURE_GROUP_NAME }} --template-file azure.json --parameters webAppName=${{ env.AZURE_WEBAPP_NAME }}
          
      # Deploy Web App
      - name: 'Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: './output' 

      # Azure logout 
      - name: logout
        run: |
          az logout